# Generated by Django 5.2.6 on 2025-09-24 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TodoList',
            new_name='Project',
        ),
        migrations.RenameModel(
            old_name='TodoItem',
            new_name='ProjectItem',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='profile_picture',
            new_name='avatar',
        ),
    ]
