# Generated by Django 5.2.6 on 2025-09-26 09:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_todolist_project_rename_todoitem_projectitem_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sharedlistaccess',
            old_name='todo_list',
            new_name='project',
        ),
        migrations.AlterUniqueTogether(
            name='sharedlistaccess',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='projectitem',
            name='is_important',
        ),
        migrations.RemoveField(
            model_name='projectitem',
            name='todo_list',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='timezone',
        ),
        migrations.AddField(
            model_name='projectitem',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_items', to='core.project'),
        ),
        migrations.AlterField(
            model_name='project',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sharedlistaccess',
            name='access_level',
            field=models.CharField(choices=[('read', 'Can read'), ('write', 'Can Edit'), ('manage', 'Can Manage')], default='read', max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AlterModelTable(
            name='project',
            table='projects',
        ),
        migrations.AlterModelTable(
            name='projectitem',
            table='project_items',
        ),
        migrations.DeleteModel(
            name='ActivityLog',
        ),
    ]
