# Generated by Django 5.2.6 on 2025-10-01 12:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_todo_list_sharedlistaccess_project_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersettings',
            name='theme',
        ),
        migrations.AddField(
            model_name='projectitem',
            name='started_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='started_tasks', to=settings.AUTH_USER_MODEL),
        ),
    ]
