# Generated by Django 5.2.7 on 2025-10-15 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='parent',
        ),
    ]
