# Generated by Django 5.2.7 on 2025-12-05 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server_manager', '0003_alter_serverinvitation_invite_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serverinvitation',
            name='email',
        ),
    ]
