# Generated by Django 5.2.7 on 2025-12-05 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_manager', '0005_alter_serverinvitation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverinvitation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', max_length=10),
        ),
    ]
