# Generated by Django 5.2.7 on 2025-12-06 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_manager', '0006_alter_serverinvitation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverinvitation',
            name='server',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='server_manager.server'),
        ),
    ]
