# Generated by Django 5.2.7 on 2025-12-06 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_manager', '0007_alter_serverinvitation_server'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverinvitation',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('moderator', 'Moderator'), ('member', 'Member')], default='member', max_length=20),
        ),
    ]
