# Generated by Django 5.2.7 on 2025-12-06 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_manager', '0008_serverinvitation_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverinvitation',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='server_manager.server'),
        ),
    ]
