# Generated by Django 5.2.7 on 2025-12-01 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_manager', '0002_initial'),
        ('server_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='server',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='server_manager.server'),
        ),
    ]
