# Generated by Django 5.2.7 on 2025-12-01 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_manager', '0003_project_server'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='is_archived',
        ),
        migrations.RemoveField(
            model_name='project',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='project',
            name='visibility',
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('planning', 'Planning'), ('active', 'Active'), ('on_hold', 'On Hold'), ('completed', 'Completed'), ('archived', 'Archived')], default='planning', max_length=20),
        ),
    ]
