# Generated by Django 5.2.7 on 2025-12-12 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_manager', '0007_projectcollaborator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectitem',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
