# Generated by Django 5.2.7 on 2025-10-15 19:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_notificationtemplate_usernotificationpreference_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='notification',
            name='notificatio_schedul_5d6388_idx',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='extra_data',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='scheduled_for',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='sent_at',
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['is_sent'], name='notificatio_is_sent_254da2_idx'),
        ),
    ]
